global.RunGML_Colors = {
	// GameMaker Colors
	"aqua": c_aqua,
	"black": c_black,
	"blue": c_blue,
	"dkgray": c_dkgray,
	"dkgrey": c_dkgrey,
	"fuchsia": c_fuchsia,
	"gray": c_gray,
	"grey": c_grey,
	"green": c_green,
	"lime": c_lime,
	"ltgray": c_ltgray,
	"ltgrey": c_ltgrey,
	"maroon": c_maroon,
	"navy": c_navy,
	"olive": c_olive,
	"orange": c_orange,
	"purple": c_purple,
	"red": c_red,
	"silver": c_silver,
	"teal": c_teal,
	"white": c_white,
	"yellow": c_yellow,
}